version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Set Up Environment
          command: |
            git submodule update --init
            ci_scripts/ci_tool.sh --setup_npm

      - restore_cache:
          key: |
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Publish
          command: ci_scripts/ci_tool.sh --npm_publish

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
workflows:
  version: 2
  build:
    jobs:
      - build
