version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: Set Up Environment
          command: |
            git submodule update --init
            ci_scripts/ci_tool.sh --setup_npm
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Calculate Version
          command: ci_scripts/ci_tool.sh --run_release
      - run:
          name: Publish
          command: ci_scripts/ci_tool.sh --npm_publish
workflows:
  version: 2
  build:
    jobs:
      - build
