version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.18.0
    steps:
      - checkout
      - run:
          name: Set Up Environment
          command: npm config set //registry.npmjs.org/:_authToken "${NPM_TOKEN}"
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Release
          command: ./scripts/release.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: 6rs-public-npm
